#!/bin/bash
#SBATCH -t 120:00:00
#SBATCH --mem=120GB
#SBATCH -c 24
#SBATCH -J canu_corr
#SBATCH -o canu_corr_out
#SBATCH -e canu_corr_err
#SBATCH -p standard


/scratch/alarracu_lab/canu-1.2/Linux-amd64/bin/canu -pacbio-corrected /scratch/alarracu_lab/dmel_blasr-corr_celera8.3/dros_corrected.u.fastq -p canu_corrected -d /scratch/alarracu_lab/dmel_canu_assemblies/canu_corrected_permissive -s /scratch/alarracu_lab/dmel_canu_assemblies/canu_default.spec genomeSize=130m useGrid=false
