#!/bin/bash
#SBATCH -J PBcR_MHAP
#SBATCH -e PBcR_MHAP_err
#SBATCH -o PBcR_MHAP_out
#SBATCH --mem-per-cpu=8000
#SBATCH -t 120:00:00
#SBATCH -c 24
#SBATCH -p standard
#SBATCH --mail-type=ALL


#sample file to run PBcR in Celera 8.3 on Bluehive cluster using slurm job manager 
module load wgs/8.3 java/1.8.0 bowtie2/2.2.1 bioperl/1.6.922


PBcR -length 500 -partitions 200 -l dmel_pacbio -s /scratch/alarracu_lab/dmel_MHAP_array/14_1500.params -fastq /scratch/dkhost/bergman_pacbio_reads/pacbio_reads_vs_celera25X_filtered+BLASR/data/filtered_subreads.fastq genomeSize=180000000 > run.out 2>&1
